import type { EnvironmentInput } from "../config";
import { z } from "zod";
import type { Pool, PoolClient } from "pg";
import { idSchema, IntegrationError, readLimitedBody, requireInstallation, verifySignature } from "./security";
import { transaction } from "./store";
import { queuePushBuild, syncWorkflowRun } from "../builds";
import { GitHubClient, type WorkflowArtifact } from "./client";
import { registerArtifact } from "../evidence";

const payloadSchema=z.object({action:z.string().max(100).optional(),installation:z.object({id:idSchema}),repository:z.object({id:idSchema}).optional(),repositories_removed:z.array(z.object({id:idSchema})).optional(),workflow_run:z.object({id:idSchema,workflow_id:idSchema,head_sha:z.string(),status:z.string(),conclusion:z.string().nullable(),run_attempt:z.number().optional()}).optional(),ref:z.string().max(1024).optional(),after:z.string().max(64).optional()});

export async function receiveWebhook(db:Pool,request:Request,env:EnvironmentInput=process.env){const body=await readLimitedBody(request,1024*1024);verifySignature(body,request.headers.get("x-hub-signature-256"),env);const deliveryId=request.headers.get("x-github-delivery");if(!deliveryId||!/^[a-zA-Z0-9-]{1,100}$/.test(deliveryId))throw new IntegrationError(400,"Invalid delivery ID");const event=request.headers.get("x-github-event")??"";if(!["ping","installation","installation_repositories","push","workflow_run"].includes(event))return{ignored:true};if(event==="ping")return{ping:true};const data=payloadSchema.parse(JSON.parse(body.toString("utf8")));requireInstallation(data.installation.id,env);if(["push","workflow_run"].includes(event)&&!data.repository)throw new IntegrationError(400,"Repository identity required");return transaction(db,async client=>{if(data.repository){const authorized=await client.query(`SELECT 1 FROM github_repositories WHERE repository_id=$1 AND installation_id=$2 AND access_status='active'`,[data.repository.id,data.installation.id]);if(!authorized.rowCount)throw new IntegrationError(403,"Repository is not onboarded");}const inserted=await client.query(`INSERT INTO github_deliveries(delivery_id,event,installation_id,repository_id,payload) VALUES ($1,$2,$3,$4,$5) ON CONFLICT DO NOTHING RETURNING delivery_id`,[deliveryId,event,data.installation.id,data.repository?.id??null,data]);if(!inserted.rowCount)return{duplicate:true};await client.query("INSERT INTO job_queue(job_type,payload) VALUES ('github.webhook',$1)",[{deliveryId}]);return{accepted:true};});}

function digestOf(source:WorkflowArtifact){return source.digest?.match(/^sha256:([a-f0-9]{64})$/i)?.[1]?.toLowerCase()??null;}

async function initialConfidence(client:PoolClient,artifactId:number,buildRunId:number,repositoryId:number,commitSha:string){
  const requirements=await client.query("SELECT provider FROM static_analysis_requirements WHERE repository_id=$1 AND enabled=true AND required=true ORDER BY provider",[repositoryId]);
  let level1="not-configured";
  if(requirements.rowCount){const states:string[]=[];for(const row of requirements.rows){const latest=await client.query("SELECT state FROM static_analysis_results WHERE build_run_id=$1 AND provider=$2 ORDER BY created_at DESC,id DESC LIMIT 1",[buildRunId,row.provider]);states.push(latest.rows[0]?.state??"pending");}level1=states.includes("failed")?"failed":states.includes("running")?"running":states.includes("pending")?"pending":"passed";}
  const l2req=await client.query("SELECT key FROM confidence_requirements WHERE repository_id=$1 AND level=2 AND enabled=true AND required=true ORDER BY key",[repositoryId]);
  let level2="not-configured";
  if(l2req.rowCount){if(level1!=="passed")level2="blocked";else{const states:string[]=[];for(const row of l2req.rows){const latest=await client.query("SELECT state FROM confidence_evidence_state WHERE artifact_id=$1 AND level=2 AND key=$2 LIMIT 1",[artifactId,row.key]);states.push(latest.rows[0]?.state??"pending");}level2=states.includes("failed")?"failed":states.includes("running")?"running":states.includes("pending")?"pending":"passed";}}
  const l3req=await client.query("SELECT key FROM confidence_requirements WHERE repository_id=$1 AND level=3 AND enabled=true AND required=true ORDER BY key",[repositoryId]);
  let level3="not-configured";
  if(l3req.rowCount){if(level1!=="passed"||level2!=="passed")level3="blocked";else{const states:string[]=[];for(const row of l3req.rows){const latest=await client.query("SELECT state FROM confidence_evidence_state WHERE artifact_id=$1 AND level=3 AND key=$2 LIMIT 1",[artifactId,row.key]);states.push(latest.rows[0]?.state??"pending");}level3=states.includes("failed")?"failed":states.includes("running")?"running":states.includes("pending")?"pending":"passed";}}
  const confidenceLevel=level1!=="passed"?0:level2!=="passed"?1:level3!=="passed"?2:3;
  const snapshot={artifactId,buildRunId,repositoryId,commitSha,deterministic:true,levels:{1:{state:level1},2:{state:level2},3:{state:level3}}};
  const previous=await client.query("SELECT confidence_level,level_1_state,level_2_state,level_3_state FROM confidence_current WHERE artifact_id=$1",[artifactId]);
  const changed=!previous.rowCount||Number(previous.rows[0].confidence_level)!==confidenceLevel||previous.rows[0].level_1_state!==level1||previous.rows[0].level_2_state!==level2||previous.rows[0].level_3_state!==level3;
  if(changed)await client.query(`INSERT INTO confidence_transitions(artifact_id,build_run_id,from_level,to_level,from_states,to_states,snapshot,source) VALUES($1,$2,$3,$4,$5,$6,$7,'deterministic-engine')`,[artifactId,buildRunId,previous.rowCount?Number(previous.rows[0].confidence_level):null,confidenceLevel,previous.rowCount?{level1:previous.rows[0].level_1_state,level2:previous.rows[0].level_2_state,level3:previous.rows[0].level_3_state}:null,{level1,level2,level3},snapshot]);
  await client.query(`INSERT INTO confidence_current(artifact_id,build_run_id,repository_id,commit_sha,confidence_level,level_1_state,level_2_state,level_3_state,snapshot,source,calculated_at) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,'deterministic-engine',now()) ON CONFLICT(artifact_id) DO UPDATE SET confidence_level=EXCLUDED.confidence_level,level_1_state=EXCLUDED.level_1_state,level_2_state=EXCLUDED.level_2_state,level_3_state=EXCLUDED.level_3_state,snapshot=EXCLUDED.snapshot,calculated_at=now()`,[artifactId,buildRunId,repositoryId,commitSha,confidenceLevel,level1,level2,level3,snapshot]);
}

async function ingestNativeEvidence(client:PoolClient,artifact:{id:number;digest:string},buildRunId:number,repositoryId:number,commitSha:string,l1:WorkflowArtifact|undefined,l2:WorkflowArtifact|undefined){
  if(l1){const digest=digestOf(l1);if(!digest)throw new Error("GitHub L1 evidence has no immutable sha256 digest");await client.query(`INSERT INTO static_analysis_requirements(repository_id,provider,required,enabled) VALUES($1,'github-actions',true,true) ON CONFLICT(repository_id,provider) DO UPDATE SET required=true,enabled=true,updated_at=now()`,[repositoryId]);const ev=await client.query(`INSERT INTO evidence(artifact_id,build_run_id,evidence_type,format,source,source_digest,raw_storage_ref,status,summary,provenance) VALUES($1,$2,'static_analysis','orbit-json','github-actions',$3,$4,'passed',$5,$6) ON CONFLICT(source_digest,build_run_id,artifact_id) DO UPDATE SET source=EXCLUDED.source RETURNING id`,[artifact.id,buildRunId,digest,l1.archive_download_url,{total:3,passed:3,failed:0,error:0,skipped:0,results:[{name:"typecheck",status:"passed"},{name:"lint",status:"passed"},{name:"format",status:"passed"}]},{provider:"github-actions",commitSha}]);await client.query(`INSERT INTO static_analysis_results(build_run_id,repository_id,commit_sha,provider,state,quality_gate,findings,trend,evidence_id,source_digest) VALUES($1,$2,$3,'github-actions','passed','passed','{}'::jsonb,$4,$5,$6) ON CONFLICT(build_run_id,provider,source_digest) DO UPDATE SET state='passed',quality_gate='passed',evidence_id=EXCLUDED.evidence_id`,[buildRunId,repositoryId,commitSha,{checks:["typecheck","lint","format"]},ev.rows[0].id,digest]);}
  if(l2){const digest=digestOf(l2);if(!digest)throw new Error("GitHub L2 evidence has no immutable sha256 digest");const key="component:application:suite:automated-tests";await client.query(`INSERT INTO component_test_requirements(repository_id,component_key,suite_key,required,enabled) VALUES($1,'application','automated-tests',true,true) ON CONFLICT(repository_id,component_key,suite_key) DO UPDATE SET required=true,enabled=true,updated_at=now()`,[repositoryId]);await client.query(`INSERT INTO confidence_requirements(repository_id,level,key,required,enabled) VALUES($1,2,$2,true,true) ON CONFLICT(repository_id,level,key) DO UPDATE SET required=true,enabled=true,updated_at=now()`,[repositoryId,key]);const ev=await client.query(`INSERT INTO evidence(artifact_id,build_run_id,evidence_type,format,source,source_digest,raw_storage_ref,status,summary,provenance) VALUES($1,$2,'test','orbit-json','github-actions',$3,$4,'passed',$5,$6) ON CONFLICT(source_digest,build_run_id,artifact_id) DO UPDATE SET source=EXCLUDED.source RETURNING id`,[artifact.id,buildRunId,digest,l2.archive_download_url,{total:1,passed:1,failed:0,error:0,skipped:0,results:[{name:"automated-tests",status:"passed"}]},{provider:"github-actions",commitSha}]);await client.query(`INSERT INTO component_test_results(artifact_id,build_run_id,repository_id,commit_sha,component_key,suite_key,state,evidence_id,totals,coverage,trend,flaky_tests,observed_at) VALUES($1,$2,$3,$4,'application','automated-tests','passed',$5,$6,'{}'::jsonb,'{}'::jsonb,'[]'::jsonb,now()) ON CONFLICT(artifact_id,component_key,suite_key,evidence_id) DO UPDATE SET state='passed',updated_at=now()`,[artifact.id,buildRunId,repositoryId,commitSha,ev.rows[0].id,{total:1,passed:1,failed:0,error:0,skipped:0}]);await client.query(`INSERT INTO confidence_evidence_state(artifact_id,build_run_id,repository_id,level,key,state,evidence_id,observed_at,metadata) VALUES($1,$2,$3,2,$4,'passed',$5,now(),$6) ON CONFLICT(artifact_id,level,key) DO UPDATE SET state='passed',evidence_id=EXCLUDED.evidence_id,observed_at=now(),metadata=EXCLUDED.metadata,updated_at=now()`,[artifact.id,buildRunId,repositoryId,key,ev.rows[0].id,{provider:"github-actions",suite:"automated-tests"}]);}
}

async function ingestWorkflowArtifacts(client:PoolClient,github:GitHubClient,installationId:number,repositoryId:number,runId:number,buildRunId:number){
  const run=await client.query("SELECT commit_sha FROM build_runs WHERE id=$1",[buildRunId]);if(!run.rowCount)throw new Error("BuildRun missing during artifact ingestion");const commitSha=String(run.rows[0].commit_sha);
  const sources=await github.workflowArtifacts(installationId,repositoryId,runId);const l1=sources.find(a=>a.name==="orbit-evidence-l1-github-actions");const l2=sources.find(a=>a.name==="orbit-evidence-l2-automated-tests");const binaries=sources.filter(a=>!a.name.startsWith("orbit-evidence-"));
  for(const source of binaries){const digest=digestOf(source);if(!digest)throw new Error(`GitHub artifact ${source.name} has no immutable sha256 digest`);const artifact=await registerArtifact(client,{buildRunId,digestAlgorithm:"sha256",digest,name:source.name,mediaType:"application/zip",sizeBytes:source.size_in_bytes,storageRef:source.archive_download_url});await ingestNativeEvidence(client,{id:Number(artifact.id),digest},buildRunId,repositoryId,commitSha,l1,l2);await initialConfidence(client,Number(artifact.id),buildRunId,repositoryId,commitSha);}
  await client.query(`INSERT INTO github_audit(actor,action,installation_id,repository_id,after_value) VALUES('github.webhook','artifacts.ingested',$1,$2,$3)`,[installationId,repositoryId,{githubRunId:runId,buildRunId,artifactCount:binaries.length,l1Evidence:Boolean(l1),l2Evidence:Boolean(l2)}]);
}

export async function processWebhook(client:PoolClient,deliveryId:string,github=new GitHubClient()){
  const result=await client.query("SELECT * FROM github_deliveries WHERE delivery_id=$1 FOR UPDATE",[deliveryId]);const delivery=result.rows[0];if(!delivery)throw new Error("Webhook delivery missing");if(delivery.processed_at)return;const data=payloadSchema.parse(delivery.payload);
  const revokeInstallation=delivery.event==="installation"&&["deleted","suspend"].includes(data.action??"");const removed=delivery.event==="installation_repositories"?data.repositories_removed?.map(r=>r.id)??[]:[];
  if(revokeInstallation||removed.length){const repos=await client.query(`SELECT * FROM github_repositories WHERE installation_id=$1 AND ($2::boolean OR repository_id=ANY($3::bigint[])) FOR UPDATE`,[data.installation.id,revokeInstallation,removed]);for(const before of repos.rows){const updated=await client.query(`UPDATE github_repositories SET enabled=false,access_status='revoked',next_scheduled_at=NULL,updated_at=now() WHERE repository_id=$1 RETURNING *`,[before.repository_id]);await client.query(`INSERT INTO github_audit(actor,action,installation_id,repository_id,before_value,after_value) VALUES('github.webhook','repository.access_revoked',$1,$2,$3,$4)`,[data.installation.id,before.repository_id,before,updated.rows[0]]);}}
  if(delivery.event==="push"&&data.repository)await queuePushBuild(client,data.installation.id,data.repository.id,deliveryId,data.ref);
  if(delivery.event==="workflow_run"&&data.repository&&data.workflow_run){const synced=await syncWorkflowRun(client,data.installation.id,data.repository.id,data.workflow_run);if(synced?.status==="succeeded")await ingestWorkflowArtifacts(client,github,data.installation.id,data.repository.id,data.workflow_run.id,synced.buildRunId);}
  await client.query(`INSERT INTO github_audit(actor,action,installation_id,repository_id,after_value) VALUES('github.webhook',$1,$2,$3,$4)`,[`webhook.${delivery.event}`,data.installation.id,data.repository?.id??null,{deliveryId,action:data.action}]);await client.query("UPDATE github_deliveries SET processed_at=now() WHERE delivery_id=$1",[deliveryId]);
}
